import jnumpy as np

def jl_mat_mul(x: np.ndarray, y: np.ndarray) -> np.ndarray: ...
def jl_mat_add(x: np.ndarray, y: np.ndarray) -> np.ndarray: ...
def jl_square(x: np.ndarray) -> np.ndarray: ...
def jl_square_grad(x: np.ndarray, dout: np.ndarray) -> np.ndarray: ...

